[build]
builder = "NIXPACKS"
buildCommand = "npm run build:backend"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "npm run start --workspace=backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
PORT = "8080"

[environments.staging]
[environments.staging.variables]
NODE_ENV = "staging"
PORT = "8080"

# Resource allocation
[resources]
memory = "1GB"
cpu = "1000m"

# Auto-scaling configuration
[scaling]
minReplicas = 1
maxReplicas = 3
targetCPU = 70
targetMemory = 80